services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicdb
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: yanisyahi/potify-backend:latest
    container_name: express-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: musicdb
      DB_HOST: db
      DB_PORT: 5432
      MUSIC_PATH: /musics
    volumes:
      - /srv/mini-spotify-data/musics:/musics

  frontend:
    image: yanisyahi/potify-frontend:latest
    container_name: angular-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db-data: