name: CI/CD pipe

on:
  push:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login, build and push docker image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/
          push: true
          tags: yanisyahi/potify-frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max


  backend-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login, build and push docker image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend/
          push: true
          tags: yanisyahi/potify-backend
          cache-from: type=gha
          cache-to: type=gha,mode=max
